spring.application.name=amazon.service.registry
server.port= 8761

#stopping self registration as a client
eureka.client.fetch-registry=false
eureka.client.registry-with-eureka=false

#setting context path
server.servlet.context-path=/registry

logger.level.org.springframework = debugger